name: Run Tests

on:
  workflow_run:
    workflows: ["Build Solution"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts

      - name: Run tests
        run: dotnet test --no-build --verbosity normal
